version: '2'
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    environment:
     - INFLUXDB_HTTP_AUTH_ENABLED=true
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD=admin
  sedaily-devops:
    build:
      context: .
    container_name: sedaily-devops
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - .:/app
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /app/node_modules/

    # Expose ports [HOST:CONTAINER]
    ports:
      - "3000:3000"

    # Set environment variables from this file
    env_file:
      - .env
